<?php
namespace App\Services\Infrastructure\Providers;
use App\Contracts\Infrastructure\CloudProviderAdapterInterface;use App\Models\ManagedServerPlan;use App\Models\ProviderConnection;use App\Models\Server;use Illuminate\Http\Client\PendingRequest;use Illuminate\Support\Facades\Http;use RuntimeException;
class HetznerCloudAdapter implements CloudProviderAdapterInterface
{
    private function client(ProviderConnection $connection):PendingRequest{return Http::baseUrl('https://api.hetzner.cloud/v1')->withToken($connection->api_token)->acceptJson()->timeout(30)->retry(2,500);}private function connection(Server $server):ProviderConnection{return$server->providerConnection??throw new RuntimeException('Provider connection is missing.');}
    public function verify(ProviderConnection $connection):array{$response=$this->client($connection)->get('/servers',['per_page'=>1])->throw();return['success'=>true,'account'=>'Hetzner Cloud project','servers_visible'=>count($response->json('servers',[]))];}
    public function create(Server $server,ManagedServerPlan $plan,array $options):array{$response=$this->client($this->connection($server))->withHeaders(['Idempotency-Key'=>'uplary-'.$server->uuid])->post('/servers',['name'=>(string)str($server->name)->slug(),'location'=>$options['region'],'server_type'=>$plan->provider_plan_id,'image'=>$options['image'],'user_data'=>$options['user_data']??null,'public_net'=>['enable_ipv4'=>true,'enable_ipv6'=>true],'labels'=>['managed'=>'true','control-plane'=>'uplary']])->throw()->json('server');return['resource_id'=>(string)$response['id'],'ip_address'=>$response['public_net']['ipv4']['ip']??'0.0.0.0','status'=>$response['status']??'initializing','region'=>$options['region'],'image'=>$options['image']];}
    public function status(Server $server):array{$s=$this->client($this->connection($server))->get('/servers/'.$server->provider_resource_id)->throw()->json('server');return['resource_id'=>(string)$s['id'],'status'=>$s['status'],'ip_address'=>$s['public_net']['ipv4']['ip']??$server->ip_address];}
    private function action(Server $server,string $action,array $payload=[]):array{$this->client($this->connection($server))->post('/servers/'.$server->provider_resource_id.'/actions/'.$action,$payload)->throw();return['resource_id'=>$server->provider_resource_id,'status'=>$action];}
    public function restart(Server $server):array{return$this->action($server,'reboot');}public function resize(Server $server,ManagedServerPlan $plan):array{return$this->action($server,'change_type',['server_type'=>$plan->provider_plan_id,'upgrade_disk'=>true]);}public function rebuild(Server $server,string $image):array{return$this->action($server,'rebuild',['image'=>$image]);}public function destroy(Server $server):array{$this->client($this->connection($server))->delete('/servers/'.$server->provider_resource_id)->throw();return['resource_id'=>$server->provider_resource_id,'status'=>'deleted'];}
}
