<?php

use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Auth\RegisteredUserController;
use App\Http\Controllers\InstallController;
use App\Http\Controllers\BrandingController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ServerConnectionController;
use App\Http\Controllers\ServerConnectionValidationController;
use App\Http\Controllers\ServerController;
use App\Http\Controllers\ServerProvisioningController;
use App\Http\Controllers\DockerComposeController;
use App\Http\Controllers\DockerContainerController;
use App\Http\Controllers\DockerImageController;
use App\Http\Controllers\DockerNetworkController;
use App\Http\Controllers\DockerVolumeController;
use App\Http\Controllers\ApplicationDeploymentController;
use App\Http\Controllers\WebApplicationController;
use App\Http\Controllers\GitWebhookController;
use App\Http\Controllers\DomainController;
use App\Http\Controllers\MonitoringController;
use App\Http\Controllers\AlertController;
use App\Http\Controllers\BackupController;
use App\Http\Controllers\OperationalLogController;
use App\Http\Controllers\ActivityController;
use App\Http\Controllers\ApiTokenController;
use App\Http\Controllers\BillingController;
use App\Http\Controllers\StripeWebhookController;
use App\Http\Controllers\TeamController;
use App\Http\Controllers\ManagedInfrastructureController;
use App\Http\Controllers\PlatformManagedInfrastructureController;
use App\Http\Controllers\HealthController;
use App\Http\Controllers\SystemHealthController;
use App\Http\Controllers\SupportController;
use App\Http\Controllers\GeneralSettingsController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\CloudInfrastructureController;
use App\Models\User;
use Illuminate\Auth\Events\PasswordReset;
use Illuminate\Foundation\Auth\EmailVerificationRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Password;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Str;

Route::redirect('/', '/dashboard');
Route::prefix('health')->middleware('throttle:120,1')->group(function (): void {
    Route::get('/live', [HealthController::class, 'live'])->name('health.live');
    Route::get('/ready', [HealthController::class, 'ready'])->name('health.ready');
});
Route::post('/hooks/git/{deployment}', GitWebhookController::class)->middleware('throttle:30,1')->name('hooks.git');
Route::post('/stripe/webhook', StripeWebhookController::class)->name('stripe.webhook');

Route::middleware('guest')->group(function (): void {
    Route::get('/install', [InstallController::class, 'create'])->name('install');
    Route::post('/install', [InstallController::class, 'store'])->middleware('throttle:10,1')->name('install.store');
    Route::get('/login', [AuthenticatedSessionController::class, 'create'])->name('login');
    Route::post('/login', [AuthenticatedSessionController::class, 'store']);
    Route::get('/register', [RegisteredUserController::class, 'create'])->name('register');
    Route::post('/register', [RegisteredUserController::class, 'store']);
    Route::get('/forgot-password', fn () => view('auth.forgot-password'))->name('password.request');
    Route::post('/forgot-password', function (Request $request) {
        $request->validate(['email' => ['required', 'email']]);
        $status = Password::sendResetLink($request->only('email'));
        return $status === Password::ResetLinkSent ? back()->with('success', __($status)) : back()->withErrors(['email' => __($status)]);
    })->name('password.email');
    Route::get('/reset-password/{token}', fn (string $token) => view('auth.reset-password', ['token' => $token, 'email' => request('email')]))->name('password.reset');
    Route::post('/reset-password', function (Request $request) {
        $request->validate(['token' => ['required'], 'email' => ['required', 'email'], 'password' => ['required', 'confirmed', 'min:8']]);
        $status = Password::reset($request->only('email', 'password', 'password_confirmation', 'token'), function (User $user, string $password): void {
            $user->forceFill(['password' => Hash::make($password), 'remember_token' => Str::random(60)])->save();
            event(new PasswordReset($user));
        });
        return $status === Password::PasswordReset ? redirect()->route('login')->with('success', __($status)) : back()->withErrors(['email' => __($status)]);
    })->name('password.update');
});

Route::middleware(['auth', 'tenant'])->group(function (): void {
    Route::get('/verify-email', fn () => view('auth.verify-email'))->name('verification.notice');
    Route::get('/verify-email/{id}/{hash}', function (EmailVerificationRequest $request) {
        $request->fulfill();
        return redirect()->route('dashboard')->with('success', 'Email address verified.');
    })->middleware('signed')->name('verification.verify');
    Route::post('/email/verification-notification', function (Request $request) {
        if ($request->user()->hasVerifiedEmail()) return back()->with('success', 'Your email is already verified.');
        $request->user()->sendEmailVerificationNotification();
        return back()->with('success', 'A new verification link has been sent.');
    })->middleware('throttle:6,1')->name('verification.send');
    Route::get('/dashboard', DashboardController::class)->middleware('verified')->name('dashboard');
    Route::get('/system-health', SystemHealthController::class)->name('system-health');
    Route::get('/support', [SupportController::class, 'index'])->name('support.index');
    Route::post('/support', [SupportController::class, 'store'])->name('support.store');
    Route::get('/support/{ticket}', [SupportController::class, 'show'])->name('support.show');
    Route::post('/support/{ticket}/replies', [SupportController::class, 'reply'])->name('support.replies.store');
    Route::put('/support/{ticket}/status', [SupportController::class, 'status'])->name('support.status');
    Route::get('/servers', [ServerController::class, 'index'])->name('servers.index');
    Route::get('/managed-infrastructure', [PlatformManagedInfrastructureController::class, 'index'])->name('managed.index');
    Route::post('/managed-infrastructure/connections', [ManagedInfrastructureController::class, 'connection'])->name('managed.connections.store');
    Route::post('/managed-infrastructure/connections/{connection}/verify', [ManagedInfrastructureController::class, 'verify'])->name('managed.connections.verify');
    Route::post('/managed-infrastructure/servers', [PlatformManagedInfrastructureController::class, 'store'])->name('managed.servers.store');
    Route::post('/managed-infrastructure/servers/{server}/action', [ManagedInfrastructureController::class, 'action'])->name('managed.servers.action');
    Route::get('/servers/create', [ServerController::class, 'create'])->name('servers.create');
    Route::post('/servers', [ServerController::class, 'store'])->name('servers.store');
    Route::post('/servers/validate-connection', ServerConnectionValidationController::class)->name('servers.validate-connection');
    Route::get('/servers/{server}/provisioning', [ServerProvisioningController::class, 'show'])->name('servers.provisioning');
    Route::get('/servers/{server}/provisioning/status', [ServerProvisioningController::class, 'status'])->name('servers.provisioning.status');
    Route::get('/servers/{server}/success', [ServerProvisioningController::class, 'success'])->name('servers.success');
    Route::post('/servers/{server}/provisioning/retry', [ServerProvisioningController::class, 'retry'])->name('servers.provisioning.retry');
    Route::post('/servers/{server}/test-connection', ServerConnectionController::class)->name('servers.test-connection');
    Route::get('/servers/{server}/details', [ServerController::class, 'details'])->name('servers.details');
    Route::post('/servers/{server}/refresh', [ServerController::class, 'refresh'])->name('servers.refresh');
    Route::get('/servers/{server}', [ServerController::class, 'show'])->name('servers.show');
    Route::delete('/servers/{server}', [ServerController::class, 'destroy'])->name('servers.destroy');
    Route::get('/containers', [DockerContainerController::class, 'index'])->name('containers.index');
    Route::post('/containers/sync', [DockerContainerController::class, 'sync'])->name('containers.sync');
    Route::post('/containers/prune', [DockerContainerController::class, 'prune'])->name('containers.prune');
    Route::post('/containers/{container}/action', [DockerContainerController::class, 'action'])->name('containers.action');
    Route::get('/images', [DockerImageController::class, 'index'])->name('images.index');
    Route::post('/images/pull', [DockerImageController::class, 'pull'])->name('images.pull');
    Route::post('/images/cleanup', [DockerImageController::class, 'cleanup'])->name('images.cleanup');
    Route::post('/images/check-updates', [DockerImageController::class, 'check'])->name('images.check');
    Route::post('/images/{image}/action', [DockerImageController::class, 'action'])->name('images.action');
    Route::get('/volumes', [DockerVolumeController::class, 'index'])->name('volumes.index');
    Route::delete('/volumes/{volume}', [DockerVolumeController::class, 'destroy'])->name('volumes.destroy');
    Route::get('/networks', [DockerNetworkController::class, 'index'])->name('networks.index');
    Route::delete('/networks/{network}', [DockerNetworkController::class, 'destroy'])->name('networks.destroy');
    Route::get('/compose', [DockerComposeController::class, 'index'])->name('compose.index');
    Route::post('/compose', [DockerComposeController::class, 'store'])->name('compose.store');
    Route::get('/applications', [ApplicationDeploymentController::class, 'index'])->name('applications.index');
    Route::get('/applications/installed', [ApplicationDeploymentController::class, 'installed'])->name('applications.installed');
    Route::get('/applications/custom', [ApplicationDeploymentController::class, 'custom'])->name('applications.custom');
    Route::get('/applications/{application}/install', [ApplicationDeploymentController::class, 'install'])->name('applications.install');
    Route::get('/applications/web/new', [WebApplicationController::class, 'create'])->name('applications.web.create');
    Route::post('/applications/web', [WebApplicationController::class, 'store'])->name('applications.web.store');
    Route::post('/deployments', [ApplicationDeploymentController::class, 'store'])->name('deployments.store');
    Route::get('/deployments/{deployment}', [ApplicationDeploymentController::class, 'show'])->name('deployments.show');
    Route::get('/deployments/{deployment}/status', [ApplicationDeploymentController::class, 'status'])->name('deployments.status');
    Route::post('/deployments/{deployment}/verify', [ApplicationDeploymentController::class, 'verify'])->name('deployments.verify');
    Route::post('/deployments/{deployment}/redeploy', [ApplicationDeploymentController::class, 'redeploy'])->name('deployments.redeploy');
    Route::post('/deployments/{deployment}/rollback/{release}', [ApplicationDeploymentController::class, 'rollback'])->name('deployments.rollback');
    Route::delete('/deployments/{deployment}', [ApplicationDeploymentController::class, 'destroy'])->name('deployments.destroy');
    Route::get('/domains', [DomainController::class, 'index'])->name('domains.index');
    Route::post('/domains', [DomainController::class, 'store'])->name('domains.store');
    Route::post('/domains/import', [DomainController::class, 'import'])->name('domains.import');
    Route::get('/domains/{domain}', [DomainController::class, 'show'])->name('domains.show');
    Route::put('/domains/{domain}', [DomainController::class, 'update'])->name('domains.update');
    Route::post('/domains/{domain}/verify', [DomainController::class, 'verify'])->name('domains.verify');
    Route::post('/domains/{domain}/configure', [DomainController::class, 'configure'])->name('domains.configure');
    Route::post('/domains/{domain}/certificate', [DomainController::class, 'certificate'])->name('domains.certificate');
    Route::delete('/domains/{domain}', [DomainController::class, 'destroy'])->name('domains.destroy');
    Route::get('/monitoring', [MonitoringController::class, 'index'])->name('monitoring.index');
    Route::post('/monitoring/collect', [MonitoringController::class, 'collect'])->name('monitoring.collect');
    Route::get('/alerts', [AlertController::class, 'index'])->name('alerts.index');
    Route::post('/alerts', [AlertController::class, 'store'])->name('alerts.store');
    Route::post('/alerts/{alert}/toggle', [AlertController::class, 'toggle'])->name('alerts.toggle');
    Route::post('/incidents/{incident}/acknowledge', [AlertController::class, 'acknowledge'])->name('incidents.acknowledge');
    Route::post('/incidents/{incident}/resolve', [AlertController::class, 'resolve'])->name('incidents.resolve');
    Route::get('/backups', [BackupController::class, 'index'])->name('backups.index');
    Route::post('/backups', [BackupController::class, 'store'])->name('backups.store');
    Route::post('/backup-schedules', [BackupController::class, 'schedule'])->name('backups.schedules.store');
    Route::post('/backup-schedules/{schedule}/toggle', [BackupController::class, 'toggleSchedule'])->name('backups.schedules.toggle');
    Route::delete('/backup-schedules/{schedule}', [BackupController::class, 'destroySchedule'])->name('backups.schedules.destroy');
    Route::post('/backup-destinations', [BackupController::class, 'destination'])->name('backups.destinations.store');
    Route::post('/backups/{backup}/restore', [BackupController::class, 'restore'])->name('backups.restore');
    Route::get('/backups/{backup}/download', [BackupController::class, 'download'])->name('backups.download');
    Route::delete('/backups/{backup}', [BackupController::class, 'destroy'])->name('backups.destroy');
    Route::get('/logs', [OperationalLogController::class, 'index'])->name('logs.index');
    Route::get('/logs/download', [OperationalLogController::class, 'download'])->name('logs.download');
    Route::get('/activity', ActivityController::class)->name('activity.index');
    Route::get('/api-tokens', [ApiTokenController::class, 'index'])->name('api-tokens.index');
    Route::post('/api-tokens', [ApiTokenController::class, 'store'])->name('api-tokens.store');
    Route::put('/api-tokens/{token}', [ApiTokenController::class, 'update'])->name('api-tokens.update');
    Route::delete('/api-tokens/{token}', [ApiTokenController::class, 'destroy'])->name('api-tokens.destroy');
    Route::get('/users', [TeamController::class, 'index'])->name('team.index');
    Route::post('/users/invitations', [TeamController::class, 'invite'])->name('team.invite');
    Route::put('/users/{member}', [TeamController::class, 'update'])->name('team.update');
    Route::post('/users/{member}/suspend', [TeamController::class, 'suspend'])->name('team.suspend');
    Route::delete('/users/{member}', [TeamController::class, 'destroy'])->name('team.destroy');
    Route::get('/billing', [BillingController::class, 'index'])->name('billing.index');
    Route::post('/billing/subscribe', [BillingController::class, 'subscribe'])->name('billing.subscribe');
    Route::post('/billing/portal', [BillingController::class, 'portal'])->name('billing.portal');
    Route::delete('/billing/subscription', [BillingController::class, 'cancel'])->name('billing.cancel');
    Route::get('/settings', [GeneralSettingsController::class, 'edit'])->name('settings');
    Route::put('/settings', [GeneralSettingsController::class, 'update'])->name('settings.update');
    Route::get('/settings/branding', [BrandingController::class, 'edit'])->name('settings.branding');
    Route::put('/settings/branding', [BrandingController::class, 'update'])->name('settings.branding.update');
    Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])->name('logout');
});

Route::prefix('admin')->name('admin.')->middleware(['auth', 'superadmin'])->group(function (): void {
    Route::get('/', [AdminController::class, 'dashboard'])->name('dashboard');
    Route::get('/settings', [AdminController::class, 'settings'])->name('settings');
    Route::put('/settings', [AdminController::class, 'updateSettings'])->name('settings.update');
    Route::get('/users', [AdminController::class, 'users'])->name('users');
    Route::post('/users', [AdminController::class, 'storeUser'])->name('users.store');
    Route::put('/users/{user}', [AdminController::class, 'updateUser'])->name('users.update');
    Route::get('/tenants', [AdminController::class, 'tenants'])->name('tenants');
    Route::get('/plans', [AdminController::class, 'plans'])->name('plans');
    Route::post('/plans', [AdminController::class, 'storePlan'])->name('plans.store');
    Route::put('/plans/{plan}', [AdminController::class, 'updatePlan'])->name('plans.update');
    Route::get('/mail', [AdminController::class, 'mail'])->name('mail');
    Route::put('/mail', [AdminController::class, 'updateMail'])->name('mail.update');
    Route::get('/payments', [AdminController::class, 'payments'])->name('payments');
    Route::put('/payments', [AdminController::class, 'updatePayments'])->name('payments.update');
    Route::get('/security', [AdminController::class, 'security'])->name('security');
    Route::put('/security', [AdminController::class, 'updateSecurity'])->name('security.update');
    Route::get('/cloud-infrastructure', [CloudInfrastructureController::class, 'index'])->name('cloud');
    Route::post('/cloud-infrastructure/connections', [CloudInfrastructureController::class, 'storeConnection'])->name('cloud.connections.store');
    Route::put('/cloud-infrastructure/connections/{c}', [CloudInfrastructureController::class, 'updateConnection'])->name('cloud.connections.update');
    Route::post('/cloud-infrastructure/connections/{c}/verify', [CloudInfrastructureController::class, 'verify'])->name('cloud.connections.verify');
    Route::post('/cloud-infrastructure/plans', [CloudInfrastructureController::class, 'storePlan'])->name('cloud.plans.store');
    Route::put('/cloud-infrastructure/plans/{p}', [CloudInfrastructureController::class, 'updatePlan'])->name('cloud.plans.update');
    Route::put('/cloud-infrastructure/markup', [CloudInfrastructureController::class, 'updateGlobalMarkup'])->name('cloud.markup.update');
});

Route::get('/invitations/{invitation}/{token}', [TeamController::class, 'accept'])->middleware('auth')->name('invitations.accept');
