<x-dashboard-layout title="Server added">
    <div class="success-page">
        <article class="success-hero"><span><i data-lucide="check"></i></span><p class="eyebrow">PROVISIONING COMPLETE</p><h1>Server successfully added</h1><p>{{ $server->name }} is online, secured, and ready for applications.</p><div><a href="{{ route('servers.show', $server) }}" class="button button--primary">View server <i data-lucide="arrow-right"></i></a><a href="#" class="button button--secondary">Deploy application</a></div></article>
        <div class="success-grid">
            <article class="card server-facts"><div class="card-head"><div><h2>Server details</h2><p>Verified installation information</p></div><span class="status status--success"><i></i> Online</span></div><dl><div><dt>Name</dt><dd>{{ $server->name }}</dd></div><div><dt>IP address</dt><dd class="mono">{{ $server->ip_address }}</dd></div><div><dt>Infrastructure</dt><dd>{{ $server->isManaged() ? 'Managed server' : $server->provider->label() }}</dd></div><div><dt>Operating system</dt><dd>{{ str($server->operating_system)->replace('-', ' ')->title() }}</dd></div><div><dt>Docker version</dt><dd>{{ $server->docker_version }}</dd></div><div><dt>Docker Compose</dt><dd>{{ $server->docker_compose_version }}</dd></div></dl></article>
            <article class="card next-actions"><div class="card-head"><div><h2>What’s next?</h2><p>Start using your new server</p></div></div><a href="#"><span class="quick-icon purple"><i data-lucide="rocket"></i></span><span><strong>Deploy your first application</strong><small>Choose a marketplace app or Docker image</small></span><i data-lucide="chevron-right"></i></a><a href="{{ route('servers.create') }}"><span class="quick-icon blue"><i data-lucide="server"></i></span><span><strong>Add another server</strong><small>Expand your infrastructure</small></span><i data-lucide="chevron-right"></i></a><a href="{{ route('servers.show', $server) }}"><span class="quick-icon green"><i data-lucide="settings-2"></i></span><span><strong>Server settings</strong><small>Review security and monitoring</small></span><i data-lucide="chevron-right"></i></a></article>
        </div>
    </div>
</x-dashboard-layout>
