<x-dashboard-layout :title="$domain->hostname">
<div class="domain-detail">
    <div class="page-heading"><div><p class="breadcrumb">Domains / {{ $domain->hostname }}</p><div class="domain-title"><span><i data-lucide="globe-2"></i></span><div><h1>{{ $domain->hostname }}</h1><p>{{ $domain->deployment?->name ?? 'Application removed' }} · {{ $domain->server?->name ?? 'Server removed' }}</p></div><em class="status status--{{ $domain->connectionApplicationComplete()?'success':($domain->status==='failed'?'failed':'warning') }}"><i></i>{{ $domain->connectionApplicationComplete()?'Active':ucfirst($domain->status) }}</em></div></div><div class="heading-actions">@if($domain->connectionApplicationComplete())<a href="https://{{ $domain->hostname }}" target="_blank" class="button button--secondary"><i data-lucide="external-link"></i> Open domain</a>@endif<a href="{{ route('domains.index') }}" class="button button--secondary"><i data-lucide="arrow-left"></i> Domains</a></div></div>
    @if($domain->failure_reason)<div class="form-alert"><i data-lucide="circle-alert"></i><div><strong>Action required</strong><p>{{ $domain->failure_reason }}</p></div></div>@endif
    <div class="domain-detail-grid"><main>
        <section class="card connection-flow"><div class="card-head"><div><h2>Connection status</h2><p>Traffic path from DNS to the application container.</p></div></div><div class="connection-steps"><div class="{{ $domain->isDnsVerified()?'is-complete':'is-pending' }}"><span><i data-lucide="radio-tower"></i></span><strong>DNS record</strong><small>{{ $domain->dnsStatusLabel() }}</small></div><i data-lucide="arrow-right"></i><div class="{{ $domain->connectionProxyComplete()?'is-complete':'is-pending' }}"><span><i data-lucide="route"></i></span><strong>Traefik route</strong><small>{{ $domain->connectionProxyComplete() ? 'Configured' : ucfirst($domain->proxy_status) }}</small></div><i data-lucide="arrow-right"></i><div class="{{ $domain->hasValidSsl()?'is-complete':'is-pending' }}"><span><i data-lucide="shield-check"></i></span><strong>SSL certificate</strong><small>{{ $domain->sslStatusLabel() }}</small></div><i data-lucide="arrow-right"></i><div class="{{ $domain->connectionApplicationReady()?'is-complete':'is-pending' }}"><span><i data-lucide="container"></i></span><strong>Application</strong><small>{{ $domain->connectionApplicationLabel() }}</small></div></div></section>
        <section class="card dns-record-card"><div class="card-head"><div><h2>DNS configuration</h2><p>Add this record at your DNS provider.</p></div><span class="status status--{{ $domain->isDnsVerified()?'success':'warning' }}"><i></i>{{ $domain->dnsStatusLabel() }}</span></div><div class="dns-record"><div><small>Type</small><code>{{ $domain->dns_record_type }}</code></div><div><small>Name / Host</small><code>{{ $domain->hostname }}</code></div><div><small>Points to / Value</small><code>{{ $domain->expected_value }}</code></div><div><small>TTL</small><code>Auto</code></div></div><div class="dns-observed"><span><i data-lucide="scan-search"></i><span><strong>Last observed</strong><small>{{ $domain->resolved_values ? implode(', ',$domain->resolved_values) : 'No public record found' }} · {{ $domain->last_dns_check_at?->diffForHumans() ?? 'Not checked' }}</small></span></span><form method="POST" action="{{ route('domains.verify',$domain) }}">@csrf<button class="button button--secondary"><i data-lucide="refresh-cw"></i> Verify DNS</button></form></div></section>
        <section class="card route-settings"><div class="card-head"><div><h2>Routing settings</h2><p>Update redirects and certificate renewal behavior.</p></div></div><form method="POST" action="{{ route('domains.update',$domain) }}">@csrf @method('PUT')<div class="form-grid form-grid--two"><label class="field field--wide"><span>Redirect destination</span><input name="redirect_to" value="{{ $domain->redirect_to }}" placeholder="Leave empty to serve the application"></label><label class="check"><input type="checkbox" name="force_https" value="1" @checked($domain->force_https)> Force HTTPS</label><label class="check"><input type="checkbox" name="auto_renew" value="1" @checked($domain->auto_renew)> Automatic certificate renewal</label></div><button class="button button--primary">Save routing</button></form></section>
    </main><aside class="domain-aside">
        <section class="card certificate-card"><span class="certificate-seal {{ $domain->hasValidSsl()?'is-valid':'' }}"><i data-lucide="shield-check"></i></span><h2>SSL certificate</h2><p>{{ $domain->certificate_provider }}</p><dl><div><dt>Status</dt><dd><span class="status status--{{ $domain->sslTone() }}"><i></i>{{ $domain->sslStatusLabel() }}</span></dd></div><div><dt>Issued</dt><dd>{{ $domain->hasValidSsl() ? ($domain->certificate_issued_at?->format('M j, Y') ?? 'Pending') : 'Pending' }}</dd></div><div><dt>Expires</dt><dd>{{ $domain->hasValidSsl() ? ($domain->certificate_expires_at?->format('M j, Y') ?? 'Pending') : 'Pending' }}</dd></div><div><dt>Renewal</dt><dd>{{ $domain->auto_renew?'Automatic':'Manual' }}</dd></div></dl>@if($domain->isDnsVerified())<form method="POST" action="{{ route('domains.certificate',$domain) }}">@csrf<button class="button button--secondary button--full"><i data-lucide="refresh-cw"></i> {{ $domain->hasValidSsl()?'Renew certificate':'Issue certificate' }}</button></form>@endif</section>
        <section class="card proxy-card"><div class="card-head"><div><h2>Reverse proxy</h2><p>Dockerized Traefik gateway.</p></div><span class="status status--{{ ($domain->server?->proxy_status ?? null)==='running'?'success':'warning' }}"><i></i>{{ ucfirst(str_replace('_',' ',$domain->server?->proxy_status ?? 'unavailable')) }}</span></div><dl><div><dt>Image</dt><dd>{{ $domain->server?->proxy_version ?? config('networking.proxy_image') }}</dd></div><div><dt>Network</dt><dd>{{ $domain->server?->proxy_network ?? config('networking.proxy_network') }}</dd></div><div><dt>HTTP</dt><dd>Port 80</dd></div><div><dt>HTTPS</dt><dd>Port 443</dd></div></dl>@if($domain->server && $domain->isDnsVerified()&&$domain->proxy_status!=='configured')<form method="POST" action="{{ route('domains.configure',$domain) }}">@csrf<button class="button button--secondary button--full">Configure proxy</button></form>@endif</section>
        <section class="card danger-card"><h3>Remove domain</h3><p>Deletes the Traefik route. The application and its data remain untouched.</p><form method="POST" action="{{ route('domains.destroy',$domain) }}">@csrf @method('DELETE')<button onclick="return confirm('Remove this domain route?')"><i data-lucide="trash-2"></i> Remove domain</button></form></section>
    </aside></div>
</div>
@if(in_array($domain->status,['pending','verifying']))<script>setTimeout(()=>location.reload(),4000)</script>@endif
</x-dashboard-layout>
