<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('docker_containers', function (Blueprint $t) { $t->id();$t->uuid('uuid')->unique();$t->foreignId('tenant_id')->constrained()->cascadeOnDelete();$t->foreignId('server_id')->constrained()->cascadeOnDelete();$t->string('docker_id')->nullable();$t->string('name');$t->string('image');$t->string('status',24)->default('created');$t->string('health',24)->nullable();$t->json('ports')->nullable();$t->decimal('cpu_percent',5,2)->default(0);$t->unsignedInteger('memory_usage_mb')->default(0);$t->unsignedInteger('memory_limit_mb')->nullable();$t->unsignedInteger('restart_count')->default(0);$t->timestamp('started_at')->nullable();$t->timestamp('finished_at')->nullable();$t->json('labels')->nullable();$t->timestamps();$t->softDeletes();$t->unique(['server_id','name']);$t->index(['tenant_id','status']); });
        Schema::create('docker_images', function (Blueprint $t) { $t->id();$t->uuid('uuid')->unique();$t->foreignId('tenant_id')->constrained()->cascadeOnDelete();$t->foreignId('server_id')->constrained()->cascadeOnDelete();$t->string('docker_id')->nullable();$t->string('repository');$t->string('tag')->default('latest');$t->string('digest')->nullable();$t->unsignedBigInteger('size_bytes')->default(0);$t->string('status',24)->default('available');$t->unsignedInteger('used_by_count')->default(0);$t->timestamp('pulled_at')->nullable();$t->boolean('update_available')->default(false);$t->json('metadata')->nullable();$t->timestamps();$t->softDeletes();$t->unique(['server_id','repository','tag']); });
        Schema::create('docker_volumes', function (Blueprint $t) { $t->id();$t->uuid('uuid')->unique();$t->foreignId('tenant_id')->constrained()->cascadeOnDelete();$t->foreignId('server_id')->constrained()->cascadeOnDelete();$t->string('docker_name');$t->string('name');$t->string('driver')->default('local');$t->string('mountpoint')->nullable();$t->unsignedBigInteger('size_bytes')->default(0);$t->string('status',24)->default('available');$t->json('labels')->nullable();$t->timestamp('backed_up_at')->nullable();$t->timestamps();$t->softDeletes();$t->unique(['server_id','docker_name']); });
        Schema::create('docker_networks', function (Blueprint $t) { $t->id();$t->uuid('uuid')->unique();$t->foreignId('tenant_id')->constrained()->cascadeOnDelete();$t->foreignId('server_id')->constrained()->cascadeOnDelete();$t->string('docker_id')->nullable();$t->string('name');$t->string('driver')->default('bridge');$t->string('scope')->default('local');$t->boolean('internal')->default(true);$t->boolean('attachable')->default(false);$t->string('subnet')->nullable();$t->string('gateway')->nullable();$t->json('labels')->nullable();$t->timestamps();$t->unique(['server_id','name']); });
        Schema::create('container_volume', function (Blueprint $t) { $t->id();$t->foreignId('docker_container_id')->constrained()->cascadeOnDelete();$t->foreignId('docker_volume_id')->constrained()->cascadeOnDelete();$t->string('mount_path');$t->boolean('read_only')->default(false);$t->timestamps();$t->unique(['docker_container_id','docker_volume_id'], 'ctr_vol_pair_uq'); });
        Schema::create('container_network', function (Blueprint $t) { $t->id();$t->foreignId('docker_container_id')->constrained()->cascadeOnDelete();$t->foreignId('docker_network_id')->constrained()->cascadeOnDelete();$t->ipAddress('ip_address')->nullable();$t->timestamps();$t->unique(['docker_container_id','docker_network_id'], 'ctr_net_pair_uq'); });
        Schema::create('docker_compose_projects', function (Blueprint $t) { $t->id();$t->uuid('uuid')->unique();$t->foreignId('tenant_id')->constrained()->cascadeOnDelete();$t->foreignId('server_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('slug');$t->longText('compose_content');$t->longText('environment')->nullable();$t->string('status',24)->default('draft');$t->timestamp('deployed_at')->nullable();$t->text('last_error')->nullable();$t->timestamps();$t->unique(['server_id','slug']); });
    }
    public function down(): void { Schema::dropIfExists('docker_compose_projects');Schema::dropIfExists('container_network');Schema::dropIfExists('container_volume');Schema::dropIfExists('docker_networks');Schema::dropIfExists('docker_volumes');Schema::dropIfExists('docker_images');Schema::dropIfExists('docker_containers'); }
};
