<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('container_metrics',function(Blueprint $t):void{$t->id();$t->foreignId('docker_container_id')->constrained()->cascadeOnDelete();$t->decimal('cpu_percent',5,2);$t->unsignedInteger('memory_usage_mb');$t->unsignedBigInteger('network_in_bytes')->default(0);$t->unsignedBigInteger('network_out_bytes')->default(0);$t->unsignedInteger('restart_count')->default(0);$t->string('health',24)->nullable();$t->timestamp('recorded_at');$t->index(['docker_container_id','recorded_at']);});
        Schema::create('backup_destinations',function(Blueprint $t):void{$t->id();$t->uuid('uuid')->unique();$t->foreignId('tenant_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('provider',30)->default('local');$t->string('endpoint')->nullable();$t->string('bucket')->nullable();$t->string('region')->nullable();$t->text('access_key')->nullable();$t->text('secret_key')->nullable();$t->boolean('active')->default(true);$t->timestamp('last_verified_at')->nullable();$t->timestamps();});
        Schema::create('backup_schedules',function(Blueprint $t):void{$t->id();$t->uuid('uuid')->unique();$t->foreignId('tenant_id')->constrained()->cascadeOnDelete();$t->foreignId('application_deployment_id')->constrained()->cascadeOnDelete();$t->foreignId('backup_destination_id')->nullable()->constrained()->nullOnDelete();$t->string('name');$t->string('backup_type',20)->default('full');$t->string('frequency',20)->default('daily');$t->string('cron_expression')->nullable();$t->unsignedSmallInteger('keep_last')->default(7);$t->unsignedSmallInteger('delete_after_days')->default(30);$t->boolean('enabled')->default(true);$t->timestamp('last_run_at')->nullable();$t->timestamp('next_run_at')->nullable();$t->timestamps();});
        Schema::create('backups',function(Blueprint $t):void{$t->id();$t->uuid('uuid')->unique();$t->foreignId('tenant_id')->constrained()->cascadeOnDelete();$t->foreignId('application_deployment_id')->constrained()->cascadeOnDelete();$t->foreignId('server_id')->constrained()->cascadeOnDelete();$t->foreignId('backup_destination_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('backup_schedule_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->string('name');$t->string('backup_type',20);$t->string('status',20)->default('pending');$t->string('storage_path')->nullable();$t->unsignedBigInteger('size_bytes')->default(0);$t->string('checksum')->nullable();$t->json('metadata')->nullable();$t->timestamp('started_at')->nullable();$t->timestamp('completed_at')->nullable();$t->timestamp('expires_at')->nullable();$t->timestamp('restored_at')->nullable();$t->text('last_error')->nullable();$t->timestamps();$t->index(['tenant_id','status']);});
        Schema::create('alert_rules',function(Blueprint $t):void{$t->id();$t->uuid('uuid')->unique();$t->foreignId('tenant_id')->constrained()->cascadeOnDelete();$t->foreignId('server_id')->nullable()->constrained()->cascadeOnDelete();$t->foreignId('docker_container_id')->nullable()->constrained()->cascadeOnDelete();$t->foreignId('application_deployment_id')->nullable()->constrained()->cascadeOnDelete();$t->string('name');$t->string('type',40);$t->string('metric',40)->nullable();$t->string('operator',5)->default('>=');$t->decimal('threshold',10,2)->nullable();$t->unsignedSmallInteger('duration_minutes')->default(5);$t->string('severity',20)->default('warning');$t->json('channels')->nullable();$t->boolean('enabled')->default(true);$t->timestamp('last_evaluated_at')->nullable();$t->timestamp('last_triggered_at')->nullable();$t->timestamps();});
        Schema::create('alert_incidents',function(Blueprint $t):void{$t->id();$t->uuid('uuid')->unique();$t->foreignId('tenant_id')->constrained()->cascadeOnDelete();$t->foreignId('alert_rule_id')->constrained()->cascadeOnDelete();$t->string('status',20)->default('open');$t->string('severity',20);$t->text('message');$t->decimal('observed_value',12,2)->nullable();$t->timestamp('triggered_at');$t->timestamp('acknowledged_at')->nullable();$t->timestamp('resolved_at')->nullable();$t->timestamps();$t->index(['tenant_id','status']);});
        Schema::create('operational_logs',function(Blueprint $t):void{$t->id();$t->foreignId('tenant_id')->constrained()->cascadeOnDelete();$t->foreignId('server_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('application_deployment_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('docker_container_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('backup_id')->nullable()->constrained()->nullOnDelete();$t->string('category',24);$t->string('severity',12)->default('info');$t->string('source')->nullable();$t->text('message');$t->json('context')->nullable();$t->timestamp('occurred_at');$t->index(['tenant_id','occurred_at']);$t->index(['tenant_id','category','severity']);});
        Schema::create('container_registries',function(Blueprint $t):void{$t->id();$t->uuid('uuid')->unique();$t->foreignId('tenant_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('provider',30);$t->string('registry_url');$t->string('username')->nullable();$t->text('token')->nullable();$t->boolean('active')->default(true);$t->timestamp('last_verified_at')->nullable();$t->timestamps();});
    }
    public function down(): void{Schema::dropIfExists('container_registries');Schema::dropIfExists('operational_logs');Schema::dropIfExists('alert_incidents');Schema::dropIfExists('alert_rules');Schema::dropIfExists('backups');Schema::dropIfExists('backup_schedules');Schema::dropIfExists('backup_destinations');Schema::dropIfExists('container_metrics');}
};
