<?php

return [
    'gates' => [
        'marketplace' => [
            'label' => 'Marketplace installs',
            'description' => 'Install curated applications from the marketplace.',
            'group' => 'Applications',
        ],
        'custom_docker' => [
            'label' => 'Custom Docker',
            'description' => 'Deploy custom images and Compose projects.',
            'group' => 'Applications',
        ],
        'git_deploy' => [
            'label' => 'Git deploy',
            'description' => 'Build and ship applications from Git repositories.',
            'group' => 'Applications',
        ],
        'managed_servers' => [
            'label' => 'Managed servers',
            'description' => 'Provision and operate fully managed servers from the platform.',
            'group' => 'Infrastructure',
            'nav' => 'managed.index',
        ],
        'cloud_api' => [
            'label' => 'Bring-your-own Cloud API',
            'description' => 'Connect a supported cloud account using your own API credentials.',
            'group' => 'Infrastructure',
            'nav' => 'cloud-api.index',
        ],
        'monitoring' => [
            'label' => 'Monitoring',
            'description' => 'Server and application metrics dashboards.',
            'group' => 'Operations',
            'nav' => 'monitoring.index',
        ],
        'alerts' => [
            'label' => 'Alert rules',
            'description' => 'Create threshold and health alert rules.',
            'group' => 'Operations',
        ],
        'backups' => [
            'label' => 'Backups',
            'description' => 'Create, schedule, and restore application backups.',
            'group' => 'Operations',
            'nav' => 'backups.index',
        ],
        's3_destinations' => [
            'label' => 'S3 backup destinations',
            'description' => 'Store backups on S3-compatible object storage.',
            'group' => 'Operations',
        ],
        'api_tokens' => [
            'label' => 'API tokens',
            'description' => 'Create scoped Cloud API credentials.',
            'group' => 'Workspace',
            'nav' => 'api-tokens.index',
        ],
        'priority_support' => [
            'label' => 'Priority support',
            'description' => 'Faster support response for production workspaces.',
            'group' => 'Workspace',
        ],
        'sla_support' => [
            'label' => 'SLA support',
            'description' => 'Contractual support SLAs for organizations.',
            'group' => 'Workspace',
        ],
        'audit_exports' => [
            'label' => 'Audit log exports',
            'description' => 'Download operational and activity log exports.',
            'group' => 'Workspace',
        ],
    ],

    'quotas' => [
        'servers' => ['label' => 'Servers', 'unit' => 'count', 'group' => 'Infrastructure'],
        'managed_servers' => ['label' => 'Managed servers', 'unit' => 'count', 'group' => 'Infrastructure'],
        'applications' => ['label' => 'Applications', 'unit' => 'count', 'group' => 'Applications'],
        'containers' => ['label' => 'Containers', 'unit' => 'count', 'group' => 'Applications'],
        'domains' => ['label' => 'Domains', 'unit' => 'count', 'group' => 'Applications'],
        'volumes' => ['label' => 'Volumes', 'unit' => 'count', 'group' => 'Applications'],
        'volume_storage_gb' => ['label' => 'Volume storage (GB)', 'unit' => 'GB', 'group' => 'Applications'],
        'team_members' => ['label' => 'Team members', 'unit' => 'count', 'group' => 'Workspace'],
        'backups' => ['label' => 'Backups', 'unit' => 'count', 'group' => 'Operations'],
        'backup_storage_gb' => ['label' => 'Backup storage (GB)', 'unit' => 'GB', 'group' => 'Operations'],
        'api_tokens' => ['label' => 'API tokens', 'unit' => 'count', 'group' => 'Workspace'],
        'monitoring_retention_days' => ['label' => 'Monitoring retention (days)', 'unit' => 'days', 'group' => 'Operations'],
    ],

    'defaults' => [
        'free' => [
            'gates' => [
                'marketplace' => true,
                'custom_docker' => true,
                'git_deploy' => false,
                'managed_servers' => false,
                'cloud_api' => false,
                'monitoring' => true,
                'alerts' => false,
                'backups' => false,
                's3_destinations' => false,
                'api_tokens' => false,
                'priority_support' => false,
                'sla_support' => false,
                'audit_exports' => false,
            ],
            'limits' => [
                'servers' => 1,
                'managed_servers' => 0,
                'applications' => 2,
                'containers' => 4,
                'domains' => 1,
                'volumes' => 4,
                'volume_storage_gb' => 10,
                'team_members' => 1,
                'backups' => 0,
                'backup_storage_gb' => 1,
                'api_tokens' => 0,
                'monitoring_retention_days' => 1,
            ],
        ],
        'starter' => [
            'gates' => [
                'marketplace' => true,
                'custom_docker' => true,
                'git_deploy' => true,
                'managed_servers' => true,
                'cloud_api' => true,
                'monitoring' => true,
                'alerts' => true,
                'backups' => true,
                's3_destinations' => false,
                'api_tokens' => true,
                'priority_support' => false,
                'sla_support' => false,
                'audit_exports' => false,
            ],
            'limits' => [
                'servers' => 3,
                'managed_servers' => 1,
                'applications' => 8,
                'containers' => 16,
                'domains' => 5,
                'volumes' => 12,
                'volume_storage_gb' => 50,
                'team_members' => 3,
                'backups' => 20,
                'backup_storage_gb' => 50,
                'api_tokens' => 3,
                'monitoring_retention_days' => 7,
            ],
        ],
        'pro' => [
            'gates' => [
                'marketplace' => true,
                'custom_docker' => true,
                'git_deploy' => true,
                'managed_servers' => true,
                'cloud_api' => true,
                'monitoring' => true,
                'alerts' => true,
                'backups' => true,
                's3_destinations' => true,
                'api_tokens' => true,
                'priority_support' => true,
                'sla_support' => false,
                'audit_exports' => true,
            ],
            'limits' => [
                'servers' => 25,
                'managed_servers' => 10,
                'applications' => 80,
                'containers' => 200,
                'domains' => 40,
                'volumes' => 80,
                'volume_storage_gb' => 500,
                'team_members' => 15,
                'backups' => 200,
                'backup_storage_gb' => 500,
                'api_tokens' => 25,
                'monitoring_retention_days' => 30,
            ],
        ],
        'business' => [
            'gates' => [
                'marketplace' => true,
                'custom_docker' => true,
                'git_deploy' => true,
                'managed_servers' => true,
                'cloud_api' => true,
                'monitoring' => true,
                'alerts' => true,
                'backups' => true,
                's3_destinations' => true,
                'api_tokens' => true,
                'priority_support' => true,
                'sla_support' => true,
                'audit_exports' => true,
            ],
            'limits' => [
                'servers' => null,
                'managed_servers' => 50,
                'applications' => null,
                'containers' => null,
                'domains' => null,
                'volumes' => null,
                'volume_storage_gb' => null,
                'team_members' => null,
                'backups' => null,
                'backup_storage_gb' => 2000,
                'api_tokens' => null,
                'monitoring_retention_days' => 90,
            ],
        ],
    ],
];
