<x-dashboard-layout title="Docker Compose"><div class="page-heading"><div><p class="breadcrumb">Docker / Compose</p><h1>Docker Compose</h1><p>Deploy multi-container projects with platform security validation.</p></div></div><div class="compose-layout"><form method="POST" action="{{ route('compose.store') }}" class="card compose-editor">@csrf<div class="wizard-card-head"><span class="section-icon"><i data-lucide="file-stack"></i></span><div><h2>Deploy Compose project</h2><p>Dangerous host capabilities and public database ports are blocked.</p></div></div><div class="form-grid form-grid--two"><label class="field"><span>Project name</span><input name="name" required placeholder="Analytics Stack"></label><label class="field"><span>Target server</span><select name="server_id" required>@foreach($servers as $s)<option value="{{ $s->id }}">{{ $s->name }} · {{ $s->ip_address }}</option>@endforeach</select></label><label class="field field--wide"><span>docker-compose.yml</span><textarea name="compose_content" class="code-editor" rows="19" required>services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:
    internal: true</textarea>@error('compose_content')<small class="field-error">{{ $message }}</small>@enderror</label><label class="field field--wide"><span>Environment variables</span><textarea name="environment" rows="5" placeholder="APP_ENV=production&#10;API_KEY=secret"></textarea><small>Stored encrypted and never included in logs.</small></label></div><div class="wizard-actions"><span></span><button class="button button--primary"><i data-lucide="rocket"></i> Validate & deploy</button></div></form><aside class="compose-aside"><article class="card requirements-card"><span class="section-icon"><i data-lucide="shield-check"></i></span><h3>Security guardrails</h3><ul><li><i data-lucide="check"></i> No privileged containers</li><li><i data-lucide="check"></i> No Docker socket or host root mounts</li><li><i data-lucide="check"></i> No host PID or networking</li><li><i data-lucide="check"></i> Databases stay on internal networks</li></ul></article><article class="card recent-projects"><div class="card-head"><div><h2>Projects</h2><p>Recent Compose deployments</p></div></div>@forelse($projects as $p)<div><span class="quick-icon purple"><i data-lucide="file-stack"></i></span><span><strong>{{ $p->name }}</strong><small>{{ $p->server?->name ?? 'Server removed' }}</small></span><span class="status status--{{ $p->status==='running'?'success':'running' }}"><i></i>{{ ucfirst($p->status) }}</span></div>@empty<p class="empty-copy">No Compose projects yet.</p>@endforelse</article></aside></div></x-dashboard-layout>
