<?php
namespace App\Http\Controllers;
use App\Enums\MembershipRole;use App\Models\ActivityLog;use App\Models\TeamInvitation;use App\Models\User;use App\Notifications\TeamInvitationNotification;use App\Services\Billing\PlanLimitService;use App\Support\TenantContext;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\Notification;use Illuminate\Support\Str;use Illuminate\Validation\Rule;use Illuminate\View\View;
class TeamController extends Controller
{
    public function index(Request $request,TenantContext $context):View{$this->manage($request);$tenant=$context->current();return view('commercial.team',['members'=>$tenant->users()->orderBy('name')->get(),'invitations'=>$tenant->invitations()->where('status','pending')->latest()->get(),'roles'=>MembershipRole::cases()]);}
    public function invite(Request $request,TenantContext $context,PlanLimitService $limits):RedirectResponse{$this->manage($request);$limits->enforce($context->current(),'team_members');$data=$request->validate(['email'=>['required','email','max:255'],'role'=>['required',Rule::enum(MembershipRole::class),Rule::notIn(['owner'])]]);abort_if($context->current()->users()->where('email',$data['email'])->exists(),422,'This user is already a member.');$token=Str::random(64);$invitation=TeamInvitation::updateOrCreate(['tenant_id'=>$context->id(),'email'=>strtolower($data['email'])],['invited_by'=>$request->user()->id,'role'=>$data['role'],'token_hash'=>hash('sha256',$token),'status'=>'pending','expires_at'=>now()->addDays(7),'accepted_at'=>null]);Notification::route('mail',$invitation->email)->notify(new TeamInvitationNotification($invitation,$token));ActivityLog::create(['tenant_id'=>$context->id(),'user_id'=>$request->user()->id,'action'=>'team.invited','description'=>$invitation->email.' invited as '.$invitation->role]);return back()->with('success','Invitation sent.')->with('invitation_url',route('invitations.accept',[$invitation,$token]));}
    public function update(Request $request,User $member,TenantContext $context):RedirectResponse{$actorRole=$this->manage($request);$membership=$context->current()->users()->whereKey($member->id)->firstOrFail();$data=$request->validate(['role'=>['required',Rule::enum(MembershipRole::class)]]);abort_if($actorRole!=='owner'&&($membership->pivot->role==='owner'||$data['role']==='owner'),403);if($membership->pivot->role==='owner'&&$data['role']!=='owner'&&$this->owners($context)===1)return back()->withErrors(['role'=>'A workspace must retain at least one owner.']);$context->current()->users()->updateExistingPivot($member->id,['role'=>$data['role']]);return back()->with('success','Member role updated.');}
    public function suspend(Request $request,User $member,TenantContext $context):RedirectResponse{$actorRole=$this->manage($request);$membership=$context->current()->users()->whereKey($member->id)->firstOrFail();abort_if($member->is($request->user()),422,'You cannot suspend yourself.');abort_if($actorRole!=='owner'&&$membership->pivot->role==='owner',403);abort_if($membership->pivot->role==='owner'&&$this->owners($context)===1,422,'The final owner cannot be suspended.');$context->current()->users()->updateExistingPivot($member->id,['is_active'=>!$membership->pivot->is_active]);return back()->with('success',$membership->pivot->is_active?'Member suspended.':'Member restored.');}
    public function destroy(Request $request,User $member,TenantContext $context):RedirectResponse{$actorRole=$this->manage($request);$membership=$context->current()->users()->whereKey($member->id)->firstOrFail();abort_if($member->is($request->user()),422,'You cannot remove yourself.');abort_if($actorRole!=='owner'&&$membership->pivot->role==='owner',403);abort_if($membership->pivot->role==='owner'&&$this->owners($context)===1,422,'The final owner cannot be removed.');$context->current()->users()->detach($member->id);return back()->with('success','Member removed.');}
    public function accept(Request $request,TeamInvitation $invitation,string $token):RedirectResponse{abort_unless(hash_equals($invitation->token_hash,hash('sha256',$token))&&$invitation->status==='pending'&&$invitation->expires_at->isFuture(),404);abort_unless(strcasecmp($request->user()->email,$invitation->email)===0,403);$invitation->tenant->users()->syncWithoutDetaching([$request->user()->id=>['role'=>$invitation->role,'is_active'=>true]]);$invitation->update(['status'=>'accepted','accepted_at'=>now()]);session(['tenant_id'=>$invitation->tenant_id]);return redirect()->route('dashboard')->with('success','Workspace invitation accepted.');}
    private function manage(Request $request):string{$role=$request->user()->tenants()->whereKey(session('tenant_id'))->first()?->pivot->role;abort_unless(in_array($role,['owner','admin'],true),403);return$role;}private function owners(TenantContext $context):int{return$context->current()->users()->wherePivot('role','owner')->wherePivot('is_active',true)->count();}
}
