<x-dashboard-layout title="Applications">
    <div class="page-heading"><div><p class="breadcrumb">Dashboard / Applications</p><h1>Application Marketplace</h1><p>Deploy trusted open-source software, Git repositories, and custom Docker images.</p></div><div class="heading-actions"><a href="{{ route('applications.installed') }}" class="button button--secondary"><i data-lucide="blocks"></i> Your applications</a><a href="{{ route('applications.web.create') }}" class="button button--secondary"><i data-lucide="git-branch"></i> Deploy from Git</a><a href="{{ route('applications.custom', array_filter(['server' => request('server')])) }}" class="button button--secondary"><i data-lucide="container"></i> Custom Docker</a><a href="#marketplace" class="button button--primary"><i data-lucide="plus"></i> Deploy application</a></div></div>
    <section class="marketplace-hero card"><div><span class="eyebrow">CURATED & VERIFIED</span><h2>Your next application, ready to deploy.</h2><p>Production-minded templates with persistent storage, health checks, secure networking, and sensible resource defaults.</p></div><span class="marketplace-orbit"><i data-lucide="rocket"></i></span></section>
    <section id="marketplace" class="marketplace-section">
        <div class="marketplace-toolbar"><form class="search-filter-form"><div class="table-search"><i data-lucide="search"></i><input name="search" value="{{ request('search') }}" placeholder="Search applications..."></div><select name="category" onchange="this.form.submit()"><option value="">All categories</option>@foreach($categories as $category)<option value="{{ $category->slug }}" @selected(request('category')===$category->slug)>{{ $category->name }}</option>@endforeach</select><select name="pricing" onchange="this.form.submit()"><option value="">All pricing</option><option value="free" @selected(request('pricing')==='free')>Free</option><option value="freemium" @selected(request('pricing')==='freemium')>Free + paid</option><option value="paid" @selected(request('pricing')==='paid')>Paid license</option></select><button class="filter-button"><i data-lucide="list-filter"></i> Filter</button></form><span>{{ $applications->count() }} verified applications</span></div>
        <div class="marketplace-grid">@forelse($applications as $app)<article class="card marketplace-card"><div class="marketplace-card-top"><x-application-icon :application="$app" class="catalog-icon" /><div class="catalog-badges"><span class="pricing-pill pricing-pill--{{ $app->pricing_model }}">{{ $app->pricingLabel() }}</span><span class="verified-pill"><i data-lucide="badge-check"></i> Verified</span></div></div><h3>{{ $app->name }}</h3><p class="catalog-category">{{ $app->category->name }} · {{ $app->licenseLabel() }}</p><p>{{ $app->description }}</p><dl><div><dt>RAM</dt><dd>{{ $app->minimum_memory_mb >= 1024 ? ($app->minimum_memory_mb/1024).' GB' : $app->minimum_memory_mb.' MB' }}</dd></div><div><dt>Storage</dt><dd>{{ $app->minimum_disk_gb }} GB</dd></div><div><dt>Version</dt><dd>{{ $app->default_tag }}</dd></div></dl>@if($app->requires_license)<p class="license-notice"><i data-lucide="key-round"></i> Vendor license required</p>@endif<a href="{{ route('applications.install', array_filter(['application' => $app, 'server' => request('server')])) }}" class="button button--primary button--full"><i data-lucide="download"></i> Install</a></article>@empty<div class="empty-state card"><span><i data-lucide="search-x"></i></span><h2>No applications found</h2><p>Try another search or deploy a custom Docker image.</p></div>@endforelse</div>
    </section>
    @if($recentDeployments->isNotEmpty())
        <section class="card" style="margin-top:20px">
            <div class="card-head"><div><h2>Recently deployed</h2><p>Your latest applications in this workspace.</p></div><a href="{{ route('applications.installed') }}">View all <i data-lucide="arrow-right"></i></a></div>
            <div class="compact-table">
                @foreach($recentDeployments as $deployment)
                    <a class="table-row" href="{{ route('deployments.show',$deployment) }}">
                        <x-application-icon :application="$deployment->application" size="sm" />
                        <span><strong>{{ $deployment->name }}</strong><small>{{ $deployment->server?->name ?? 'Server unavailable' }}</small></span>
                        <span class="status status--{{ in_array($deployment->status->value,['running','completed'],true) ? 'success' : ($deployment->status->value === 'failed' ? 'failed' : 'running') }}"><i></i>{{ ucfirst($deployment->status->value) }}</span>
                        <time>{{ $deployment->created_at->diffForHumans() }}</time>
                        <i data-lucide="chevron-right"></i>
                    </a>
                @endforeach
            </div>
        </section>
    @endif
</x-dashboard-layout>
