@php($adminNav=[['Overview','layout-dashboard','admin.dashboard'],['General Settings','settings-2','admin.settings'],['Branding','palette','admin.branding'],['Users','users','admin.users'],['Tenants','building-2','admin.tenants'],['Subscription Plans','badge-dollar-sign','admin.plans'],['SMTP & Email','mail','admin.mail'],['Payment Gateways','credit-card','admin.payments'],['Cloud Infrastructure','cloud-cog','admin.cloud'],['Security','shield-check','admin.security']])
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>{{ $title ?? 'Platform Admin' }} Â· Uplary</title>@vite(['resources/css/app.css','resources/js/app.js'])<link rel="stylesheet" href="{{ asset('admin-console.css') }}?v=4"><link rel="stylesheet" href="{{ asset('admin-cloud.css') }}?v=2"><link rel="stylesheet" href="{{ asset('admin-plans.css') }}?v=2"></head>
<body class="app-body" x-data="{adminNav:false}"><div class="admin-shell"><aside class="admin-sidebar" :class="adminNav&&'is-open'"><a class="admin-brand" href="{{ route('admin.dashboard') }}"><span><i data-lucide="layers-3"></i></span><strong>Uplary</strong><em>SUPERADMIN</em></a><nav>@foreach($adminNav as [$label,$icon,$route])<a href="{{ route($route) }}" class="{{ request()->routeIs($route)||request()->routeIs($route.'.*')?'is-active':'' }}"><i data-lucide="{{ $icon }}"></i>{{ $label }}</a>@endforeach</nav><div class="admin-sidebar-foot"><a href="{{ route('dashboard') }}"><i data-lucide="arrow-left"></i>Return to tenant console</a><form method="post" action="{{ route('logout') }}">@csrf<button><i data-lucide="log-out"></i>Sign out</button></form></div></aside><main class="admin-main"><header class="admin-topbar"><button @click="adminNav=!adminNav"><i data-lucide="menu"></i></button><span><strong>Platform Console</strong><small>Global administration</small></span><div><span class="avatar">{{ str(auth()->user()->name)->substr(0,2)->upper() }}</span><span><strong>{{ auth()->user()->name }}</strong><small>Super Administrator</small></span></div></header><section class="admin-content">
@if(session('success'))
    <div class="admin-alert"><i data-lucide="circle-check"></i>{{ session('success') }}</div>
@endif
@if($errors->any())
    <div class="admin-alert admin-alert--error"><i data-lucide="triangle-alert"></i>{{ $errors->first() }}</div>
@endif
{{ $slot }}
</section></main></div></body></html>
