<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;use App\Models\ManagedServerPlan;use App\Models\ProviderConnection;use App\Services\Infrastructure\CloudProviderFactory;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Validation\Rule;use Illuminate\View\View;use Throwable;
class CloudInfrastructureController extends Controller{
public function index():View{return view('admin.cloud',['connections'=>ProviderConnection::where('platform_managed',true)->latest()->get(),'plans'=>ManagedServerPlan::orderBy('provider')->orderBy('position')->get()]);}
public function storeConnection(Request $r,CloudProviderFactory $f):RedirectResponse{$d=$r->validate(['name'=>'required|string|max:100','provider'=>['required',Rule::in(['digitalocean','hetzner'])],'api_token'=>'required|string|max:2000','account_id'=>'nullable|string|max:255','active'=>'nullable|boolean']);$c=ProviderConnection::create($d+['tenant_id'=>null,'platform_managed'=>true,'active'=>$r->boolean('active')]);return$this->check($c,$f,'Cloud connection saved and verified.');}
public function updateConnection(Request $r,ProviderConnection $c,CloudProviderFactory $f):RedirectResponse{abort_unless($c->platform_managed,404);$d=$r->validate(['name'=>'required|string|max:100','api_token'=>'nullable|string|max:2000','account_id'=>'nullable|string|max:255','active'=>'nullable|boolean']);if(blank($d['api_token']??null))unset($d['api_token']);$c->update($d+['active'=>$r->boolean('active')]);return isset($d['api_token'])?$this->check($c,$f,'Cloud connection updated and verified.'):back()->with('success','Cloud connection updated.');}
public function verify(ProviderConnection $c,CloudProviderFactory $f):RedirectResponse{abort_unless($c->platform_managed,404);return$this->check($c,$f,'Cloud API verified successfully.');}
public function storePlan(Request $r):RedirectResponse{ManagedServerPlan::create($this->planData($r));return back()->with('success','Managed server plan created.');}
public function updatePlan(Request $r,ManagedServerPlan $p):RedirectResponse{$p->update($this->planData($r,$p));return back()->with('success','Managed server plan updated.');}
public function updateGlobalMarkup(Request $r):RedirectResponse{$d=$r->validate(['markup_percentage'=>'required|numeric|min:0|max:1000']);$markup=(int)round($d['markup_percentage']);ManagedServerPlan::where('active',true)->each(function(ManagedServerPlan $plan)use($markup){$plan->update(['markup_percentage'=>$markup,'monthly_price'=>(int)round($plan->monthly_cost*(1+$markup/100))]);});return back()->with('success',$markup.'% markup applied to every published managed server plan.');}
private function planData(Request $r,?ManagedServerPlan $p=null):array{$d=$r->validate(['provider'=>['required',Rule::in(['digitalocean','hetzner'])],'provider_plan_id'=>['required','string','max:100',Rule::unique('managed_server_plans')->where('provider',$r->provider)->ignore($p)],'name'=>'required|string|max:100','cpu_cores'=>'required|integer|min:1','memory_mb'=>'required|integer|min:512','disk_gb'=>'required|integer|min:10','bandwidth_gb'=>'nullable|integer|min:0','monthly_cost'=>'required|numeric|min:0','markup_percentage'=>'required|numeric|min:0|max:1000','currency'=>'required|string|size:3','regions'=>'required|string','images'=>'required|string','featured'=>'nullable|boolean','active'=>'nullable|boolean']);$cost=(int)round($d['monthly_cost']*100);$markup=(int)round($d['markup_percentage']);$d['monthly_cost']=$cost;$d['markup_percentage']=$markup;$d['monthly_price']=(int)round($cost*(1+$markup/100));$d['regions']=$this->csv($d['regions']);$d['images']=$this->csv($d['images']);$d['featured']=$r->boolean('featured');$d['active']=$r->boolean('active');$d['position']=$p?->position??(ManagedServerPlan::max('position')+1);return$d;}
private function csv(string $v):array{return collect(explode(',',$v))->map(fn($i)=>trim($i))->filter()->values()->all();}
private function check(ProviderConnection $c,CloudProviderFactory $f,string $m):RedirectResponse{try{$f->make($c)->verify($c);$c->update(['last_verified_at'=>now(),'last_error'=>null]);return back()->with('success',$m);}catch(Throwable $e){$c->update(['last_verified_at'=>null,'last_error'=>$e->getMessage(),'active'=>false]);return back()->withErrors(['provider'=>$e->getMessage()]);}}
}
